// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWBUObFDIbTJofNY0bCQvt4YOXnCJLq0',
    appId: '1:594081431498:web:741ebf1a83205a0f2fd933',
    messagingSenderId: '594081431498',
    projectId: 'smart-chata-486f1',
    authDomain: 'smart-chata-486f1.firebaseapp.com',
    storageBucket: 'smart-chata-486f1.firebasestorage.app',
    measurementId: 'G-7GYYTV6WD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkm-b9IaYwZcBQKNaPdudIoUE6xJ2131g',
    appId: '1:594081431498:android:fd720b1f2da01db22fd933',
    messagingSenderId: '594081431498',
    projectId: 'smart-chata-486f1',
    storageBucket: 'smart-chata-486f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokMslF_Kcc9dG-w3q2pkaymMAlhepU90',
    appId: '1:594081431498:ios:1471124b8092312e2fd933',
    messagingSenderId: '594081431498',
    projectId: 'smart-chata-486f1',
    storageBucket: 'smart-chata-486f1.firebasestorage.app',
    iosBundleId: 'com.example.smartChata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgWBUObFDIbTJofNY0bCQvt4YOXnCJLq0',
    appId: '1:594081431498:web:62ad9776482061a12fd933',
    messagingSenderId: '594081431498',
    projectId: 'smart-chata-486f1',
    authDomain: 'smart-chata-486f1.firebaseapp.com',
    storageBucket: 'smart-chata-486f1.firebasestorage.app',
    measurementId: 'G-YGQ92F9TP2',
  );
}
